project/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path("", views.index, name="index"),
]

project/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path("maklar/", views.maklar, name="maklar"),
    path("fk/", views.fk, name="fk"),
    path("lyyski/", views.lyyski, name="lyyski"),
    path("aktia/", views.aktia, name="aktia"),
    path("analytics/", views.analytics, name="analytics"),
    path('form/', views.create_form_house, name='form'),
    path('page/', views.page, name='page'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

from allauth.account.views import PasswordResetView

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/password/reset/', PasswordResetView.as_view(), name='password_reset'),

    path("", include("core.urls")),
    path("", include("pages.urls")),
    re_path(r'^rosetta/', include('rosetta.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# for url patterns domain/language/uri/
# urlpatterns += i18n_patterns(
#     path('accounts/', include('allauth.urls')),
#     path('accounts/password/reset/', PasswordResetView.as_view(), name='password_reset'),

#     path("", include("core.urls")),
#     prefix_default_language=False,
# ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/models.py
from django.db import models

from django.dispatch import receiver
from allauth.account.signals import user_signed_up
from allauth.socialaccount.signals import social_account_added

from django.contrib.auth.models import Group

@receiver(user_signed_up)
@receiver(social_account_added)
def add_user_to_group(request, user, **kwargs):
    group_name = 'default'  # Replace with the actual group name

    try:
        group = Group.objects.get(name=group_name)
        user.groups.add(group)
    except Group.DoesNotExist:
        pass

project/core/forms.py
# forms.py
from django import forms
from pages.models import MaklerHouse, FkHouse, LyyskiHouse

class HouseSearchForm(forms.Form):
    search_query = forms.CharField(required=False)
    min_price = forms.DecimalField(required=False, min_value=0)
    max_price = forms.DecimalField(required=False, min_value=0)

project/core/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from pages.utils.mongodb import get_mongodb_connection
from datetime import datetime
from pages.models import MaklerHouse, FkHouse, LyyskiHouse, AktiaHouse, MapData
from django.db.models import Q
import re
from urllib.parse import urlparse

def index(request):

    query = request.GET.get('query', '')
    max_price = request.GET.get('max_price')
    min_price = request.GET.get('min_price')
    page_number = request.GET.get('page', 1)  # Get the page number from the request
    sort_option = request.GET.get('sort')
    selected_municipality = request.GET.get('municipality')
    selected_type = request.GET.get('type')


    # Create individual querysets for each house type
    makler_markets = MaklerHouse.objects.order_by('-date_added')
    fk_markets = FkHouse.objects.order_by('-date_added')
    lyyski_markets = LyyskiHouse.objects.order_by('-date_added')
    aktia_markets = AktiaHouse.objects.order_by('-date_added')

    # Get unique municipalities from all house types
    unique_municipalities = set()
    unique_municipalities.update(makler_markets.values_list('municipality', flat=True))
    unique_municipalities.update(fk_markets.values_list('municipality', flat=True))
    unique_municipalities.update(lyyski_markets.values_list('municipality', flat=True))
    unique_municipalities.update(aktia_markets.values_list('municipality', flat=True))

    # Get unique types from all house types
    unique_types = set()
    unique_types.update(makler_markets.values_list('type', flat=True))
    unique_types.update(fk_markets.values_list('type', flat=True))
    unique_types.update(lyyski_markets.values_list('type', flat=True))
    unique_types.update(aktia_markets.values_list('type', flat=True))

    # Filter out None values and sort
    municipalities = sorted(filter(None, unique_municipalities))
    types = sorted(filter(None, unique_types))

    # Apply query and price filters to each queryset
    if query:
        keywords = query.split()
        query_filter = Q()

        for keyword in keywords:
            query_filter |= Q(name__icontains=keyword) | Q( municipality__icontains=keyword) | Q( address__icontains=keyword ) | Q( type__icontains=keyword)

        makler_markets = makler_markets.filter(query_filter)
        fk_markets = fk_markets.filter(query_filter)
        lyyski_markets = lyyski_markets.filter(query_filter)
        aktia_markets = aktia_markets.filter(query_filter)

    if max_price:
        max_price_int = int(max_price)
        makler_markets = makler_markets.filter(price__lte=max_price_int)
        fk_markets = fk_markets.filter(price__lte=max_price_int)
        lyyski_markets = lyyski_markets.filter(price__lte=max_price_int)
        aktia_markets = aktia_markets.filter(price__lte=max_price_int)

    if min_price:
        min_price_int = int(min_price)
        makler_markets = makler_markets.filter(price__gte=min_price_int)
        fk_markets = fk_markets.filter(price__gte=min_price_int)
        lyyski_markets = lyyski_markets.filter(price__gte=min_price_int)
        aktia_markets = aktia_markets.filter(price__gte=min_price_int)

    # Filter based on selected municipality
    if selected_municipality:
        makler_markets = makler_markets.filter(municipality=selected_municipality)
        fk_markets = fk_markets.filter(municipality=selected_municipality)
        lyyski_markets = lyyski_markets.filter(municipality=selected_municipality)
        aktia_markets = aktia_markets.filter(municipality=selected_municipality)

    # Filter based on selected type
    if selected_type:
        makler_markets = makler_markets.filter(type=selected_type)
        fk_markets = fk_markets.filter(type=selected_type)
        lyyski_markets = lyyski_markets.filter(type=selected_type)
        aktia_markets = aktia_markets.filter(type=selected_type)



    # Combine querysets for pagination
    combined_markets = list(makler_markets) + list(fk_markets) + list(lyyski_markets) + list(aktia_markets)
    
    if sort_option == 'highest_price':
        combined_markets.sort(key=lambda x: x.price if x.price is not None else float('-inf'), reverse=True)
    elif sort_option == 'lowest_price':
        combined_markets.sort(key=lambda x: x.price if x.price is not None else float('inf'))

    # Paginate the combined queryset
    per_page = 10  # Number of items per page
    paginator = Paginator(combined_markets, per_page)
    page_obj = paginator.get_page(page_number)

    # Calculate the range of page numbers to display in the paginator
    current_page = page_obj.number
    page_range = range(max(1, current_page - 5), min(current_page + 6, paginator.num_pages + 1))

    

    houses = {
        'query': query,
        'max_price': max_price,
        'min_price': min_price,
        'page_obj': page_obj,
        'municipality': request.GET.get('municipality'),  # Get the municipality from the request for select
        'type': request.GET.get('type'),  # Get the type from the request for select
        'page_range': page_range,  # Add the calculated page range to the houses dictionary

    }  

 
#! ANALYTICS DAta

    db_name_avg_price = 'average_price'
    db_avg_price = get_mongodb_connection(db_name_avg_price)
    collection_avg_price = db_avg_price[f"data_{datetime.now().strftime('%Y-%m-%d')}"]

    # Get the first document from the collection
    avg_price = collection_avg_price.find_one()

    # Extract specific fields excluding '_id'
    if avg_price:
        avg_price_fields = {
            'date': avg_price['date'],
            'average_price_maklar': avg_price['average_price_maklar'],
            'average_price_fk': avg_price['average_price_fk'],
            'average_price_lyyski': avg_price['average_price_lyyski'],
            'overall_average_price': avg_price['overall_average_price']
        }
    else:
        avg_price_fields = None


    db_name_avg_floor_price = 'average_floor_price'
    db_avg_floor_price = get_mongodb_connection(db_name_avg_floor_price)
    collection_avg_floor_price = db_avg_floor_price[f"data_{datetime.now().strftime('%Y-%m-%d')}"]

    # Get the first document from the collection
    avg_floor_price = collection_avg_floor_price.find_one()

    # Extract specific fields excluding '_id'
    if avg_floor_price:
        avg_floor_price_fields = {
            'date': avg_floor_price['date'],
            'average_cost_per_area_maklar': avg_floor_price['average_cost_per_area_maklar'],
            'average_cost_per_area_fk': avg_floor_price['average_cost_per_area_fk'],
            'average_cost_per_area_lyyski': avg_floor_price['average_cost_per_area_lyyski'],
            'overall_average_cost_per_area': avg_floor_price['overall_average_cost_per_area']
        }
    else:
        avg_floor_price_fields = None

    #? Extra data

    # Modify the extraction logic for market names and domains
    for market in combined_markets:
        parsed_url = urlparse(market.link)
        domain_name = parsed_url.netloc.split(':')[0]  # Extract the domain name without port
        market.domain_name = domain_name  # Store the extracted domain name


    # Create a list of links from the combined_markets queryset
    combined_links = [market.link for market in combined_markets]

    # Filter map_data to include only those with links present in the combined_links list
    filtered_map_data = MapData.objects.filter(unique_identifier__in=combined_links)

    # Filter out data points with no address from filtered_map_data
    filtered_map_data = filtered_map_data.exclude(address='No address')

    context = {
        'avg_price': avg_price_fields, 
        'avg_floor_price': avg_floor_price_fields,  
        'houses': houses,
        'combined_markets': combined_markets,
        'municipalities': municipalities,  # Pass the municipalities to the template
        'types': types,  # Pass the types to the template
        'request': request,
        'map_data': filtered_map_data
    }


    return render(request, 'core/index.html', context)

project/core/templates/core/base.html
{% load static i18n  %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <title>{% block title %}{% endblock %}</title>

    {% get_current_language as LANGUAGE_CODE %}
    <link rel="icon" type="image/x-icon" href="{% static 'flags/' %}{{ LANGUAGE_CODE }}.svg">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500&display=swap" rel="stylesheet">
    <!--Bootstrap-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}?{% now "U"%}">

    <!-- Leaflet-->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>

    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.5.0/dist/MarkerCluster.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.5.0/dist/MarkerCluster.Default.css" />
    <script src="https://unpkg.com/leaflet.markercluster@1.5.0/dist/leaflet.markercluster.js"></script>





    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    


</head>
<body class=" bg-dark text-light">
    {% include "core/header.html"%}
        {% block content %}
        {% endblock %}
</body>
</html>

project/core/templates/core/header.html
{% load static i18n %}

<style>

    #title-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
    }

    #title {
        width: fit-content;
    }

    .user-dropdown .dropdown-menu {
        left: 50% !important;
        transform: translateX(-50%) !important;
        top: 100% !important;
      }

      .dropdown-item:hover {
        background-color: #1D2124;
        border-radius: .2rem;
      }

</style>

<header class="p-2 bg-secondary text-white">
    <div class="d-flex flex-wrap justify-content-center align-items-center w-100">

        <div id="title-container" class="w-100">
        <a href="{% url 'core:index' %}" id="title" class="h4 my-auto my-2 title text-white text-center">{% trans 'Åland House Market' %}</a>
        </div>
            <!-- Links -->
            <div class="d-flex justify-content-end align-items-center my-auto" style="max-width: fit-content;">
                    <!-- If not logged in, login button-->
                    {% if request.user.is_authenticated %}
                        
                        {% if request.path != '/profile/' %} <!-- Add this line -->
                            <a href="{% url 'account_email' %}" class="btn btn-primary btn-sm mx-1 my-1">{{ request.user.username|truncatechars:14 }}</a>
                        {% endif %}                            
                        <!-- Nav burger-->
                        <a class="btn  btn-primary btn-sm mx-1 my-1" data-toggle="collapse" href="#collapseNav" role="button" aria-expanded="false" aria-controls="collapseNav">
                            &#9776;
                        </a>

                        <a href="{% url 'account_logout' %}" class="small text-muted mx-1" title="{% trans 'Click to logout!' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-power" width="16" height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M7 6a7.75 7.75 0 1 0 10 0" />
                                <path d="M12 4l0 8" />
                              </svg>
                        </a>
                    {% else %}
                        <a href="{% url 'account_login' %}" class="btn btn-primary btn-sm mx-2 my-1">{% trans 'Login' %}</a>
                        <a href="{% url 'account_signup' %}" class="btn btn-primary  btn-sm mx-2 my-1">{% trans 'Signup' %}</a>
                    {% endif %}

                    <div id="google_translate_element"></div>


                    {% get_current_language as LANGUAGE_CODE %}
                    <div class="language-selector">
                        <img src="{% static 'flags/' %}{{ LANGUAGE_CODE }}.svg" class="language-icon rounded img-fluid h-100 ml-2 user-select-none" alt="{{ LANGUAGE_CODE }}" width="40" height="30">
                        <form id="language-form" action="{% url 'set_language' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ redirect_to }}">
                            
                            
                            <select class="mx-1 text-center" name="language" id="language-select">
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                {% for language in languages %}
                                <option class="bg-dark text-light" value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>{% trans language.code %}</option>
                                {% endfor %}
                            </select>

                            
                        </form>
                    </div>
                    
                    
                    <script>
                        document.getElementById('language-select').addEventListener('change', function() {
                            document.getElementById('language-form').submit();
                        });
                    </script>
                    
                      
            </div>

        </div>

    {% if request.user.is_authenticated %}
    <div class="collapse" id="collapseNav">
        <div class="d-flex col-sm-auto justify-content-center align-items-center">


            <div class="dropdown">
                <button class="btn btn-dark btn-sm mx-1 my-1 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {% trans 'Markets' %}
                </button>
                <div class="dropdown-menu dropdown-menu-right bg-dark mt-1" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item text-light" href="{% url 'pages:maklar' %}">Maklar</a>
                  <a class="dropdown-item text-light" href="{% url 'pages:fk' %}">Fk</a>
                  <a class="dropdown-item text-light" href="{% url 'pages:lyyski' %}">Lyyski</a>
                  <a class="dropdown-item text-light" href="{% url 'pages:aktia' %}">Aktia</a>
                </div>
              </div>

              
            <div class="dropdown">
                <button class="btn btn-dark btn-sm mx-1 my-1 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {% trans 'Tools' %}
                </button>
                <div class="dropdown-menu dropdown-menu-left bg-dark mt-1" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item text-light" href="{% url 'pages:analytics' %}">{% trans 'Analytics' %}</a>
                  <a class="dropdown-item text-light" href="{% url 'pages:form' %}">{% trans 'Form' %}</a>
                  <a class="dropdown-item text-light" href="#"> {% trans 'History' %}</a>
                </div>
              </div>

            <a href="" class="p-2 btn-sm text-muted ">{% trans 'Contact' %}</a>
        </div>
    </div>
    {% endif %}
</header>